const Experience = [
  {
    name: "GhostSwap.finance",
    url: "https://www.ghostswap.finance/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Created all pages and components for a web3 automated market maker that supports pool creation for any BNB collection",
      "Designed and implemented launchpad page for minting and distributing new web3 assets",
      "Assisted with connecting component interactions with web3 contracts and backend services",
    ],
    timeframe: "2022 - 2023",
    location: "Remote",
    sectionName: "ghostswap",
  },
  {
    name: "LittleGhosts.io",
    url: "https://littleghosts.io/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Updated colors and styles across the entire application",
      "Added a shop page enabling users to purchase or mint digital assets for in game use",
      "Extended features for inventory tab",
      "Updated node backend to be able to support invocation of Python 3.10 scripts in order to add a popular python package for ranking a collection of rare digital assets",
    ],
    timeframe: "2023 - 2024",
    location: "Remote",
    sectionName: "littleghosts",
  },
  {
    name: "Phantasma MMO",
    url: "https://littleghosts.io/",
    role: "Fullstack Engineer/Game Dev - Freelance",
    description: "",
    details: [
      "Built UI components to support common MMO features",
      "Created world map, mini map, coordinate display, bank, backpack, crafting, looting, xp, and drag/drop systems",
      "Crafted various particle effects for dashing and loot drops",
      "Handled replication of data between client and server to prevent invalid data and cheating",
      "Implemented persistence of dropped loot items, combat xp, crafting xp, and player inventories",
    ],
    timeframe: "2024 - 2024",
    location: "Remote",
    sectionName: "phantasma",
  },
  {
    name: "Atlantis.fun",
    url: "https://atlantis-frontend-ochre.vercel.app/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Initialized via fork of older project, updated dependencies, removed unneeded packages, optimized build with SWC",
      "Developed a majority of the site components, layout, and UX while ensuring full responsiveness for mobile platforms",
      "Leveraged Shadcn component library, enabled progressive web app features, compiled and hosted dev build on vercel",
      "Implemented editable User and Group profiles with avatar image support, text and image posts, and leaderboards",
      'Benchmarked and improved backend queries. Developed "posts" and "watched tokens" features from end to end',
    ],
    timeframe: "2024 - 2025",
    location: "Remote",
    sectionName: "atlantis",
  },
  {
    name: "Drip.market",
    url: "",
    role: "Code Janitor/Frontend Engineer - Freelance",
    description: "",
    details: [
      "Hired to clean up and maintain pages produced by AI agents in the codebase for a web3 marketplace",
      "Refactored monolithic collections page from 9000+ lines of code to ~700 lines of code (~92% reduction) while preserving all functionality",
      "Maintained and improved existing codebase while implementing new features and ensuring full responsiveness for mobile platforms",
      "Continuously implemented pixel perfect UI changes to match rapidly evolving design requirements from the product team",
      "Standardized styles to reduce inconsistencies across the entire codebase",
    ],
    timeframe: "2025 - 2025",
    location: "Remote",
    sectionName: "drip",
  },
  {
    name: "DataAnnotation.tech",
    url: "https://www.dataannotation.tech",
    role: "Contract Software Engineer",
    description: "",
    details: [
      "Evaluating and rating the quality of AI-generated outputs to compare and rank various industry-leading LLM model performance against each other",
      "Providing high-quality inputs for Reinforced Learning with Human Feedback (RLHF) to help improve the quality of AI-generated code",
      "Validating the effectiveness of custom finetuned models in controlled environments to test regression and evaluate viablity of proprietary classified/private LLMs",
      "Crafting complex, reusable `API` prompts with multi-layered hierarchical rules to stress-test reliability and prioritization of LLM instruction following",
      "Rating, reviewing, and editing submissions from other DataAnnotation contractors to improve alignment and correctness of human feedback to be used as training data",
    ],
    timeframe: "2025 - 2026 (Present)",
    location: "Remote",
    sectionName: "dataannotation",
  },
];

export default Experience;
