const Experience = [
  {
    name: "GhostSwap.finance",
    url: "https://www.ghostswap.finance/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Created all pages and components for a web3 automated market maker that supports pool creation for any BNB collection",
      "Designed and implemented launchpad page for minting and distributing new web3 assets",
      "Assisted with connecting component interactions with web3 contracts and backend services",
    ],
    timeframe: "2022 - 2023",
    location: "Remote",
    sectionName: "ghostswap",
  },
  {
    name: "LittleGhosts.io",
    url: "https://littleghosts.io/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Updated colors and styles across the entire application",
      "Added a shop page enabling users to purchase or mint digital assets for in game use",
      "Extended features for inventory tab",
      "Updated node backend to be able to support invocation of Python 3.10 scripts in order to add a popular python package for ranking a collection of rare digital assets",
    ],
    timeframe: "2023 - 2024",
    location: "Remote",
    sectionName: "littleghosts",
  },
  {
    name: "Phantasma MMO",
    url: "https://littleghosts.io/",
    role: "Fullstack Engineer/Game Dev - Freelance",
    description: "",
    details: [
      "Built UI components to support common MMO features",
      "Created world map, mini map, coordinate display, bank, backpack, crafting, looting, xp, and drag/drop systems",
      "Crafted various particle effects for dashing and loot drops",
      "Handled replication of data between client and server to prevent invalid data and cheating",
      "Implemented persistence of dropped loot items, combat xp, crafting xp, and player inventories",
    ],
    timeframe: "2024 - 2024",
    location: "Remote",
    sectionName: "phantasma",
  },
  {
    name: "Atlantis.fun",
    url: "https://atlantis-frontend-ochre.vercel.app/",
    role: "Fullstack Engineer - Freelance",
    description: "",
    details: [
      "Initialized via fork of older project, updated dependencies, removed unneeded packages, optimized build with SWC",
      "Developed a majority of the site components, layout, and UX while ensuring full responsiveness for mobile platforms",
      "Leveraged Shadcn component library, enabled progressive web app features, compiled and hosted dev build on vercel",
      "Implemented editable User and Group profiles with avatar image support, text and image posts, and leaderboards",
      'Benchmarked and improved backend queries. Developed "posts" and "watched tokens" features from end to end',
    ],
    timeframe: "2024 - 2025",
    location: "Remote",
    sectionName: "atlantis",
  },
];

export default Experience;
